package com.Sufi.zoodex.util

object IconUtils {
    fun getAnimalIcon(animalName: String): String {
        return when (animalName.uppercase()) {
            "VOLT HOUND" -> "🐕"
            "STORM EAGLE" -> "🦅"
            "MAGMA GORILLA" -> "🦍"
            "NEON TIGER" -> "🐯"
            "GLITCH SPECTER" -> "👻"
            "SOLAR HAWK" -> "🦅"
            "VOID FLYER" -> "🦇"
            "EMERALD COBRA" -> "🐍"
            "STREET CAT" -> "🐱"
            "STRAY DOG" -> "🐕"
            "HOUSE SPARROW" -> "🕊️"
            "COMMON CROW" -> "🐦"
            "PARK SQUIRREL" -> "🐿️"
            "MARKHOR" -> "🐐"
            "SNOW LEOPARD" -> "🐆"
            "HIMALAYAN IBEX" -> "🐐"
            "MONAL PHEASANT" -> "🐦"
            "DESERT SAND-CAT" -> "🐱"
            "INDUS DOLPHIN" -> "🐬"
            "SHELTER CORAL" -> "🪸"
            "PALLAS CAT" -> "🐱"
            "GOLDEN EAGLE" -> "🦅"
            "RIVER OTTER" -> "🦦"
            "KINGFISHER" -> "🐦"
            "GIANT CATFISH" -> "🐟"
            "FROG" -> "🐸"
            "GHARIAL" -> "🐊"
            "INDIAN RHINOCEROS" -> "🦏"
            "TORTOISE" -> "🐢"
            "WILD BOAR" -> "🐗"
            "BADGER" -> "🦡"
            "BURROWING OWL" -> "🦉"
            "BENGAL TIGER" -> "🐯"
            "ASIAN ELEPHANT" -> "🐘"
            "SLOTH BEAR" -> "🐻"
            "CLOUDED LEOPARD" -> "🐆"
            "PANGOLIN" -> "🦑"
            "HORNBILL" -> "🐦"
            "KING COBRA" -> "🐍"
            "PEACOCK" -> "🦚"
            "SAMBAR DEER" -> "🦌"
            "NILGAI ANTELOPE" -> "🦌"
            "WILD WATER BUFFALO" -> "🐃"
            "ASIAN PALM CIVET" -> "🐱"
            "PEAFOWL" -> "🦚"
            "HYENA" -> "🐕"
            "JACKAL" -> "🐕"
            "MONITOR LIZARD" -> "🦎"
            "FLYING SQUIRREL" -> "🐿️"
            "FISHING CAT" -> "🐱"
            "SARUS CRANE" -> "🦢"
            "SACRED MONKEY" -> "🐵"
            "PYTHON" -> "🐍"
            "WILD DOG PACK ALPHA" -> "🐕"
            "GREAT HORNBILL" -> "🐦"
            "CLOUDY VISION BAT" -> "🦇"
            "TARANTULA HAWK" -> "🦅"
            "WILD BOAR TUSKER" -> "🐗"
            "PORCUPINE" -> "🦔"
            "MONGOOSE" -> "🦡"
            else -> "🐾"
        }
    }
}
